### ISSUE TITLE
Do not log debug messages as errors

### ISSUE THREAD

**Issue by jonherrmann** [interactive-instruments/etf-gmlgeox#17]
Etf log files are flooded with messages like this:

```
2017-08-03 11:41:49.492 [TestRun.bfc9fe61-85fe-4aec-b9fc-336c3354acd5] ERROR d.i.e.b.GmlGeoX - [Notice] [null] [Thu Aug 03 11:41:49 CEST 2017] - Detected GML standard version: GML3.2.
```

Actually this looks like a debug message logged as an error from here

https://github.com/interactive-instruments/etf-gmlgeox/blob/master/src/main/java/de/interactive_instruments/etf/bsxm/GmlGeoX.java#L582

and here

https://github.com/interactive-instruments/etf-gmlgeox/blob/master/src/main/java/de/interactive_instruments/etf/bsxm/GmlGeoX.java#L540

**Comment by jonherrmann** [comment]
Ok, after realizing this message is logged about **900 times per second**, we should treat this as bug.

**Comment by jechterhoff** [comment]
It should be straightforward to exclude validation messages with specific types, like in this case NOTICE. Other types are FATAL, ERROR and WARNING. 

I wonder if we should even remove logging in these two places, since the validation messages are returned in the query result (when validateAndReport() is called).

**Comment by jonherrmann** [comment]
Ok, thanks, then I will remove the logging code.
