### ISSUE TITLE
Question: Xpath to GML Features in any type of collection

### ISSUE THREAD

**Issue by thijsbrentjens** [interactive-instruments/etf-gmlgeox#6]
In the Geometry tests an XPath is needed to determine which elements are the features. If we know the GML application schema

e.g. for IMGeo, we have:
`//cit:cityObjectMember/*`

But for a WFS featurecollection we would need something like:
`//wfs:FeatureCollection/wfs:member/*`
or 
`//wfs:member/*`

I find it hard to determine a generic Xpath, that would find features in any type of featurecollection. Does someone have a suggestion how to deal with this?

**Comment by cportele** [comment]
Unfortunately not. The problem is that BaseX is not schema-aware, so //schema-element(gml:AbstractFeature) does not work. In general I have used something like "/wfs:FeatureCollection/wfs:member/* | /gml:FeatureCollection/gml:featureMember/* | ...". Not very pretty, but a more general solution would require support for something like //schema-element(gml:AbstractFeature) based on an analysis of the schema. In SoapUI we have a function that does that, maybe that could be reused in some way in the BaseX context?

**Comment by jonherrmann** [comment]
The free Saxon-HE version does not support the schema-element function, neither. I only see a chance by reusing the code from the SoapUI extension etf-owsgtl.

**Comment by thijsbrentjens** [comment]
Okay. For now the xpath of @cportele will be sufficient. And we could also make the xpath a parameter if we need to have more control over it per test.
